'''
constants.py

The constants found in here represent mappings from our rigs to other standards.

There's a "generic" mapping, that is a go-between, so even our in-house standard isn't permanent 
in the tool.
'''

# The generic map is a list of the keys for which other data sets connect.  This is INTENTIONALLY
# different from our in-house standard.
GENERIC_KEYS=[
    'trajectory','spine_hip','spine_chest','spine_chest_tip','neck_base','neck_tip','head_base',
    'head_tip',
    'left_clavicle','left_shoulder','left_elbow','left_wrist',
    'left_pinky_0','left_pinky_1','left_pinky_2','left_pinky_3','left_pinky_4',
    'left_ring_0','left_ring_1','left_ring_2','left_ring_3','left_ring_4',
    'left_middle_0','left_middle_1','left_middle_2','left_middle_3','left_middle_4',
    'left_index_0','left_index_1','left_index_2','left_index_3','left_index_4',
    'left_thumb_1','left_thumb_2','left_thumb_3','left_thumb_4','left_thumb_5',
    'right_clavicle','right_shoulder','right_elbow','right_wrist',
    'right_pinky_0','right_pinky_1','right_pinky_2','right_pinky_3','right_pinky_4',
    'right_ring_0','right_ring_1','right_ring_2','right_ring_3','right_ring_4',
    'right_middle_0','right_middle_1','right_middle_2','right_middle_3','right_middle_4',
    'right_middle_5',
    'right_index_0','right_index_1','right_index_2','right_index_3','right_index_4',
    'right_thumb_1','right_thumb_2','right_thumb_3','right_thumb_4',
    'left_hip','left_knee','left_ankle','left_ball','left_toe','right_hip','right_knee',
    'right_ankle','right_ball','right_toe',
]


# SR_bones we have and know:
SR_MAPPING={
    'trajectory':'trajectory_SHJnt',
    'spine_hip':'spineHip_SHJnt',
    'spine_chest':'spineChest_SHJnt',
    'spine_chest_tip':'spineChestTip_SHJnt',
    'neck_base':'neckBase_SHJnt',
    'neck_tip':'neckHead_SHJnt',
    'head_base':'',
    'head_tip':'',
    'left_clavicle':'L_shoulder_SHJnt',
    'left_shoulder':'L_armUpr_SHJnt',
    'left_elbow':'L_armLwr_SHJnt',
    'left_wrist':'L_armWrist_SHJnt',
    'left_pinky_0':'L_pinky_01_SHJnt',
    'left_pinky_1':'L_pinky_02_SHJnt',
    'left_pinky_2':'L_pinky_03_SHJnt',
    'left_pinky_3':'L_pinky_04_SHJnt',
    'left_pinky_4':'L_pinky_05_SHJnt',
    'left_pinky_5':'',
    'left_ring_0':'L_ring_01_SHJnt',
    'left_ring_1':'L_ring_02_SHJnt',
    'left_ring_2':'L_ring_03_SHJnt',
    'left_ring_3':'L_ring_04_SHJnt',
    'left_ring_4':'L_ring_05_SHJnt',
    'left_ring_5':'',
    'left_middle_0':'L_middle_01_SHJnt',
    'left_middle_1':'L_middle_02_SHJnt',
    'left_middle_2':'L_middle_03_SHJnt',
    'left_middle_3':'L_middle_04_SHJnt',
    'left_middle_4':'L_middle_05_SHJnt',
    'left_middle_5':'',
    'left_index_0':'L_middle_01_SHJnt',
    'left_index_1':'L_middle_02_SHJnt',
    'left_index_2':'L_middle_03_SHJnt',
    'left_index_3':'L_middle_04_SHJnt',
    'left_index_4':'L_middle_05_SHJnt',
    'left_thumb_1':'L_thumb_01_SHJnt',
    'left_thumb_2':'L_thumb_02_SHJnt',
    'left_thumb_3':'L_thumb_03_SHJnt',
    'left_thumb_4':'L_thumb_04_SHJnt',
    'left_thumb_5':'',
    'right_clavicle':'R_shoulder_SHJnt',
    'right_shoulder':'R_armUpr_SHJnt',
    'right_elbow':'R_armLwr_SHJnt',
    'right_wrist':'R_armWrist_SHJnt',
    'right_pinky_0':'R_pinky_01_SHJnt',
    'right_pinky_1':'R_pinky_02_SHJnt',
    'right_pinky_2':'R_pinky_03_SHJnt',
    'right_pinky_3':'R_pinky_04_SHJnt',
    'right_pinky_4':'R_pinky_05_SHJnt',
    'right_pinky_5':'',
    'right_ring_0':'R_ring_01_SHJnt',
    'right_ring_1':'R_ring_02_SHJnt',
    'right_ring_2':'R_ring_03_SHJnt',
    'right_ring_3':'R_ring_04_SHJnt',
    'right_ring_4':'R_ring_05_SHJnt',
    'right_ring_5':'',
    'right_middle_0':'R_middle_01_SHJnt',
    'right_middle_1':'R_middle_02_SHJnt',
    'right_middle_2':'R_middle_03_SHJnt',
    'right_middle_3':'R_middle_04_SHJnt',
    'right_middle_4':'R_middle_05_SHJnt',
    'right_middle_5':'',
    'right_index_0':'R_middle_01_SHJnt',
    'right_index_1':'R_middle_02_SHJnt',
    'right_index_2':'R_middle_03_SHJnt',
    'right_index_3':'R_middle_04_SHJnt',
    'right_index_4':'R_middle_05_SHJnt',
    'right_index_5':'',
    'right_thumb_1':'R_thumb_01_SHJnt',
    'right_thumb_2':'R_thumb_02_SHJnt',
    'right_thumb_3':'R_thumb_03_SHJnt',
    'right_thumb_4':'R_thumb_04_SHJnt',
    'right_thumb_5':'',

    'left_hip':'L_legUpr_SHJnt',
    'left_knee':'L_legLwr_SHJnt',
    'left_ankle':'L_legAnkle_SHJnt',
    'left_ball':'L_footMid_SHJnt',
    'left_toe':'',
    'right_hip':'R_legUpr_SHJnt',
    'right_knee':'R_legLwr_SHJnt',
    'right_ankle':'R_legAnkle_SHJnt',
    'right_ball':'R_footMid_SHJnt',
    'right_toe':''
}