# deform.py
# Created: Monday, 14th February 2022 8:32:59 am
# Matthew Riche
# Last Modified: Monday, 14th February 2022 8:33:05 am
# Modified By: Matthew Riche

'''
Operations related to deformations
'''

from . import component as cmp
from . import progbar as prg

import pymel.core as pm

def deltas_to_tweak(new_geo, old_geo, tweak):
    '''
    Applies a list of vertex deltas, generated by component.list_vertex_deltas() to the inside
    of a tweak node.
    '''

    

    deltas = cmp.list_vertex_deltas(new_geo, old_geo)

    prg.start_progbar(max_value=len(deltas), message="Baking Deltas to Tweak node...")

    for i in range(0, len(deltas)):
        tweak_vert = tweak.plist[0].controlPoints[i]
        tweak_vert.xValue.set(deltas[i][0])
        tweak_vert.yValue.set(deltas[i][1])
        tweak_vert.zValue.set(deltas[i][2])
        prg.update_progbar()

    prg.end_progbar()

    print("Vertex deltas from {} are now baked to {}.".format(new_geo.name(), tweak))

    return

